### ISSUE TITLE
Option to keep semicolons

### ISSUE THREAD

**Issue by elgs** [vknabel/vscode-swiftformat#14]
What should I add to the options to keep semicolons? Thanks.

**Comment by vknabel** [comment]
Hi @elgs.

To configure the formatting of your code you can either add a `.swiftformat`-configuration-file or set the `swiftformat.options`-setting in VS Code.

On how to configure SwiftFormat please head to [nicklockwood/SwiftFormat](https://github.com/nicklockwood/SwiftFormat). They even have a list of all possible [Rules](https://github.com/nicklockwood/SwiftFormat/blob/master/Rules.md).

You can disable the removal of all semicolons using `--disable semicolons`.

Here using the config file
```
# .swiftformat
--disable semicolons
```

Here just within vscode
```json
// .vscode/settings.json
{
  "swiftformat.options": ["--disable", "semicolons"]
}
```

**Comment by elgs** [comment]
```
// .vscode/settings.json
{
  "swiftformat.options": ["--disable", "semicolons"]
}
```

This doesn't seem to work.

![2020-10-02 14 44 37](https://user-images.githubusercontent.com/55955/94972350-edce9180-04bd-11eb-97e9-4db9c4617b07.gif)

**Comment by vknabel** [comment]
Hi @elgs. I released an update. `swiftformat.options` was ignored if it contained no `--config`.
Now it should work as expected.

**Comment by elgs** [comment]
Vielen Dank! Es macht!
