### ISSUE TITLE
How is swiftformat.options configured?

### ISSUE THREAD

**Issue by xxxIxxxx** [vknabel/vscode-swiftformat#17]
<img width="787" alt="image" src="https://user-images.githubusercontent.com/20101165/141730956-8cd4d0c3-730b-42cd-a49b-105575244400.png">

It doesn't seem to work that way.
So can you add a configuration list like this one?
Thanks big guy!
---
好像不是这样用的。
那么可以加一个像这样的配置列表吗？
谢谢大佬！

**Comment by vknabel** [comment]
Hi @xxxIxxxx, sorry for the late response!

The correct config would be: `"swiftformat.options": ["--stripunusedargs", "closure-only"]`.
Does it work for you that way? It seems like you configured `"swiftformat.options": ["--stripunusedargs closure-only"]` instead.

**Comment by xxxIxxxx** [comment]
Thanks for the reply, I tried it and it still doesn't work
```
 "--stripunusedargs", "closure-only"    or    "--stripunusedargs","closure-only"
❌ SwiftFormat failed. error: File not found at /"--stripunusedargs".

 --stripunusedargs, closure-only    or    --stripunusedargs,closure-only
❌ SwiftFormat failed. error: Unknown option --stripunusedargs, closure-only. Did you mean --stripunusedargs?

 --stripunusedargs
❌ SwiftFormat failed. error: --stripunusedargs option expects a value.
```
<img width="577" alt="1" src="https://user-images.githubusercontent.com/20101165/148870072-d3f664ca-ff61-4f3c-bb45-eafe99e36ff9.png">

**Comment by vknabel** [comment]
That's weird. 

You are on Linux, right?

What happens if you uncheck `Swiftformat: Only enable on Swift PM Projects`, remove the dependency from your Package.swift, run `swift package clean` and reopen the VS Code window?

Maybe there is a bug when using the Package directly from your Swift PM project.

**Comment by xxxIxxxx** [comment]
macOS

Unchecking it doesn't work, I only have an A.swift file

<img width="463" alt="1" src="https://user-images.githubusercontent.com/20101165/148908494-71d24ba2-182e-4910-99e4-8120e27fe5d7.png">
