### ISSUE TITLE
Always adds `--header "// Created {created}"` to format command

### ISSUE THREAD

**Issue by jsonfry** [vknabel/vscode-swiftformat#19]
Looks like a recent change now always adds a file header on formatting

https://github.com/vknabel/vscode-swiftformat/commit/9f6af87a5e3487292c9def33979057fffffd26c8

**Comment by vknabel** [comment]
Thanks a lot @jsonfry!
Good catch! I committed some debugging code.

Just released a fix in [v1.3.9](https://github.com/vknabel/vscode-swiftformat/releases/tag/v1.3.9). Sorry for the inconvenience!

**Comment by jsonfry** [comment]
No worries, thanks for the quick fix!

**Comment by jsonfry** [comment]
Guten Morgen. I think something must have gone wrong with the release, it seems that code is still in the package you download from VS Marketplace

<img width="1197" alt="image" src="https://user-images.githubusercontent.com/368400/153830490-f5213901-563a-44c5-9275-4931929fea3d.png">

**Comment by vknabel** [comment]
@jsonfry good morning, too! The `vscode:prepublish`-step to compile the project was missing. 😅
Should be fixed in 1.3.10
