### ISSUE TITLE
SwiftFormat failed. error: File not found

### ISSUE THREAD

**Issue by bxqgit** [vknabel/vscode-swiftformat#21]
OS: Windows 10
SwiftFormat: Latest
vscode-swiftformat: Latest

Error message appears, when trying to format a file:

`SwiftFormat failed. error: File not found at C:/Users/foo/AppData/Local/Programs/Microsoft VS Code/c:/prj/Foo/Sources/Foo/main.swift.`

For some reason extension uses the wrong path of the file.

The correct path of the file is `C:/prj/Foo/Sources/Foo/main.swift`

But extension tries to find it at `C:/Users/foo/AppData/Local/Programs/Microsoft VS Code/c:/prj/Foo/Sources/Foo/main.swift`

**Comment by vknabel** [comment]
Thanks for the report. I'll try to have a look on this soon.

**Comment by vknabel** [comment]
@bxqgit I just released an update which _should_ fix your issue. But due to the lack of a windows computer or VM I couldn't confirm the fix.
