### ISSUE TITLE
Not working when swift project is inside /src

### ISSUE THREAD

**Issue by matas-ramanauskas-revel** [vknabel/vscode-swiftformat#26]
So I have this project structure:

```
- tests
- deployment_thingies
- src
    - Package.swift
    - main.swift
    - .swiftforat
```

This plugin does not work (and gives no error too). If I open only src in VS Code, then it works as expected.

More info:
I'm using swiftFormat pas package dependancy

**Comment by vknabel** [comment]
Ithaka for the feedback. I’ll have a look on this.

**Comment by vknabel** [comment]
This has been fixed and will be included in the next release
