### ISSUE TITLE
Better Format Selection

### ISSUE THREAD

**Issue by MahdiBM** [vknabel/vscode-swiftformat#27]
When you do "Format Selection" in VSCode, it'll format the selection out of context of the file, which can make it look weird because it won't properly take care of indentation etc...

It should instead take the whole file context into account, but only modify the selected lines.

#### 1:
<img width="236" alt="Screenshot 2023-08-11 at 2 32 17 AM" src="https://github.com/vknabel/vscode-swiftformat/assets/54685446/0286ad91-437b-484b-a102-935d7654eb2b">

#### 2:
<img width="242" alt="Screenshot 2023-08-11 at 2 32 24 AM" src="https://github.com/vknabel/vscode-swiftformat/assets/54685446/e39ebdb9-80a5-4972-a9ca-47d24ebde370">

#### 3:
<img width="646" alt="Screenshot 2023-08-11 at 2 32 34 AM" src="https://github.com/vknabel/vscode-swiftformat/assets/54685446/5879c2c8-3f84-420c-9743-5126d05e28e5">

#### 4:
<img width="223" alt="Screenshot 2023-08-11 at 2 32 48 AM" src="https://github.com/vknabel/vscode-swiftformat/assets/54685446/2ebe9946-db06-415b-ac20-931a3e6e3440">

As you can see, in 4 indentation of the function is broken compared to the parent struct. There is also a weird extra space below the function after the indentation, not sure why.

### Usage?

When working on team projects you might want to keep your own code-style clean, but don't force it on others.
Without a feature like this you always need to format the whole file instead of just the few lines you wrote.

**Comment by vknabel** [comment]
Thanks for opening this issue! I totally get the use case and I definitely will have a look on this.

**Comment by MahdiBM** [comment]
I just noticed this issue in swift-format repo: https://github.com/apple/swift-format/issues/297
I though doesn't hurt to mention that they basically want to natively support what this issue requests.

**Comment by MahdiBM** [comment]
I just notice this is the repository for Nick Lokwood's swift-format, but actually that makes the issue even better because i've now moved to the Nick Lockwood's swiftformat because Apple's swift-format is doesn't seem actually useable in practically formatting stuff _properly_.

**Comment by vknabel** [comment]
Thanks for the upcoming comments!
If I get this right, there is no issue in this repo and for the apple formatter extension, this is an upstream issue.
