### ISSUE TITLE
Report  Cannot read property 'uri' of undefined

### ISSUE THREAD

**Issue by cchitsiang** [vknabel/vscode-swiftformat#3]
`TypeError: Cannot read property 'uri' of undefinedat Object.swiftFormatPath (/Users/cs/.vscode/extensions/vknabel.vscode-swiftformat-1.2.1/out/src/Current.js:113:58)at format (/Users/cs/.vscode/extensions/vknabel.vscode-swiftformat-1.2.1/out/src/SwiftFormatEditProvider.js:23:52)at SwiftFormatEditProvider.provideDocumentFormattingEdits (/Users/cs/.vscode/extensions/vknabel.vscode-swiftformat-1.2.1/out/src/SwiftFormatEditProvider.js:51:16)at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:557:303at t.asThenable (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:141:941)at new Promise (<anonymous>)at Object.t.asThenable (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:141:909)at e.provideDocumentFormattingEdits (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:557:262)at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:572:705at e._withAdapter (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:567:513)at e.$provideDocumentFormattingEdits (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:572:667)at t._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:658:837)at t._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:658:509)at t._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:657:60)at t._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:656:59)at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:653:895at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:130:793at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:133:218)at a (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:186:147)at Socket.n._socketDataListener (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:186:368)at emitOne (events.js:116:13)at Socket.emit (events.js:211:7)at addChunk (_stream_readable.js:263:12)at readableAddChunk (_stream_readable.js:250:11)at Socket.Readable.push (_stream_readable.js:208:10)at Pipe.onread (net.js:594:20)`

**Comment by vknabel** [comment]
Thanks for reporting your issue. I guess the stacktrace is enough to fix this bug soon. 👍

**Comment by vknabel** [comment]
Fix has been released as [1.2.2](https://github.com/vknabel/vscode-swiftformat/releases/tag/1.2.2). If this does not solve your use case, we can re-open this issue and have another deeper look on this.

**Comment by cchitsiang** [comment]
Verified, solved. Thanks for this!
