### ISSUE TITLE
Error: SwiftFormat failed. error: Cannot combine stdin with other file inputs.

### ISSUE THREAD

**Issue by samishchandra** [vknabel/vscode-swiftformat#35]
Receiving following error.

SwiftFormat failed. error: Cannot combine stdin with other file inputs.

![image](https://github.com/vknabel/vscode-swiftformat/assets/2313133/cc24ca02-e039-429a-94b9-d40f4f73c9ec)

**Comment by vknabel** [comment]
Hi @samishchandra, has this ever happened again for you? And if: after which action? Do you have some special settings?

**Comment by vknabel** [comment]
As I currently neither use Swift nor VS Code, I‘d be happy to receive a PR. Though I believe this issues has been fixed by another change or wasn’t related to this extension. Feel free to reopen.
