### ISSUE TITLE
Latest release (v1.6.8) broke swiftformat path (macOS/Linux).

### ISSUE THREAD

**Issue by furby-tm** [vknabel/vscode-swiftformat#39]
The latest release here https://github.com/vknabel/vscode-swiftformat/releases/tag/v1.6.8, has broken the path to find the `swiftformat` executable, at least on Fedora Linux, forcing me to revert to **v1.6.7**.

Upon formatting swift code with **v1.6.8**, this extension now errors with the following:
![image](https://github.com/vknabel/vscode-swiftformat/assets/18516968/0ff82ea4-469d-48bf-8050-b999a40585e3)

No matter if the path is valid or not.

Thanks!

**Comment by arietis** [comment]
It affects macOS as well.

**Comment by vinocher-bc** [comment]
Thanks for the report. Am looking at this now.
