### ISSUE TITLE
Report ENOENT spawnSync /usr/local/bin/swiftformat ENOENT

### ISSUE THREAD

**Issue by lukstruck** [vknabel/vscode-swiftformat#4]
`Error: spawnSync /usr/local/bin/swiftformat ENOENTat _errnoException (util.js:1024:11)at spawnSync (child_process.js:591:20)at Object.execFileSync (child_process.js:628:13)at Object.module.(anonymous function) [as execFileSync] (ELECTRON_ASAR.js:166:20)at format (/Users/admin/.vscode/extensions/vknabel.vscode-swiftformat-1.2.1/out/src/SwiftFormatEditProvider.js:23:14)at SwiftFormatEditProvider.provideDocumentFormattingEdits (/Users/admin/.vscode/extensions/vknabel.vscode-swiftformat-1.2.1/out/src/SwiftFormatEditProvider.js:51:16)at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:557:303at t.asThenable (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:141:941)at new Promise (<anonymous>)at Object.t.asThenable (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:141:909)at e.provideDocumentFormattingEdits (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:557:262)at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:572:705at e._withAdapter (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:567:513)at e.$provideDocumentFormattingEdits (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:572:667)at t._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:658:837)at t._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:658:509)at t._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:657:60)at t._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:656:59)at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:653:895at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:130:793at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:133:218)at a (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:186:147)at Socket.n._socketDataListener (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:186:368)at emitOne (events.js:116:13)at Socket.emit (events.js:211:7)at addChunk (_stream_readable.js:263:12)at readableAddChunk (_stream_readable.js:250:11)at Socket.Readable.push (_stream_readable.js:208:10)at Pipe.onread (net.js:594:20)`

**Comment by vknabel** [comment]
Before actually being able to format swift code, you need to have SwiftFormat installed and the extension must be able to find it.

See https://github.com/vknabel/vscode-swiftformat/blob/master/README.md for more details.
In case `$ which swiftformat` returns `/usr/local/bin/swiftformat` or if you have added SwiftFormat as dependency for your Swift Package Manager project, I will have another deeper look on this.
