### ISSUE TITLE
On-type formatting doesn't appear to work

### ISSUE THREAD

**Issue by tristanlabelle** [vknabel/vscode-swiftformat#42]
I'm not getting formatting when hitting enter (we're currently registering it for "\n" characters), nor after modifying it to "}", when I type that character.

**Comment by MahdiBM** [comment]
@tristanlabelle Are you on the latest version? Works fine for me on 1.7.0.

**Comment by vinocher-bc** [comment]
@MahdiBM did you mean [1.6.9](https://github.com/vknabel/vscode-swiftformat/blob/1981730be4e11aefef4a0ebb7b5ae21974c18c1a/package.json#L9), which seems to be the latest version? Currently, formatting on Enter isn't working for me either on Windows in version 1.6.9.

**Comment by MahdiBM** [comment]
Ah i had manually installed a version 1.7.0 locally with my own changes. Regardless, when I enable format-on-type:
```json
"editor.formatOnType": true
```
it just works for me.

**Comment by vinocher-bc** [comment]
`"editor.formatOnType": true` was missing. Thanks.

**Comment by MahdiBM** [comment]
Perhaps there should be some documentation for that, that we add 🙂.

**Comment by vinocher-bc** [comment]
Shouldn't `provideOnTypeFormattingEdits` format the previous line if ch === '\n',  since the current line after an Enter will almost always be empty?
