### ISSUE TITLE
Extension causes VS Code to ask macOS permissions to read unrelated folders

### ISSUE THREAD

**Issue by davidalejandroaguilar** [vknabel/vscode-swiftformat#44]
Hi,

I'm getting prompts asking to grant permissions to unrelated folders when saving a file located in: `/Users/david/src/swift/UnitConversions/UnitConversions/ContentView.swift`

I saw that [nicklockwood/SwiftFormat](https://github.com/nicklockwood/SwiftFormat)'s repo has a warning:

>WARNING: swiftformat . will overwrite any Swift files it finds in the current directory, and any subfolders therein. If you run it in your home directory, it will probably reformat every Swift file on your hard drive.

I'm wondering if this extension accidentally caused that.

![image](https://github.com/vknabel/vscode-swiftformat/assets/15317732/eb54d2db-4c80-4aad-bdd3-345219fa84cd)
![image](https://github.com/vknabel/vscode-swiftformat/assets/15317732/a0346e3e-ffde-490c-802e-56e917faa26c)
![image](https://github.com/vknabel/vscode-swiftformat/assets/15317732/bad6f268-8784-472e-834f-4270d9aa229a)
![image](https://github.com/vknabel/vscode-swiftformat/assets/15317732/7f84f0eb-3797-49a8-8898-62733a76e4b9)

**Comment by vknabel** [comment]
Hi @davidalejandroaguilar,
thanks for the report. This is a bug when searching for your swiftformat binary when editing single files outside of workspaces. At least it wouldn't have formatted all your code.
Working on a fix.

**Comment by davidalejandroaguilar** [comment]
Ahh interesting, glad you found the bug!

Just to clarify, the extension was only searching for the binary, and not formatting every Swift file it found in those folders, right?

**Comment by vknabel** [comment]
Correct. It didn’t want to format all those folders
