### ISSUE TITLE
Report  Cannot read property 'uri' of undefined

### ISSUE THREAD

**Issue by joy-yu** [vknabel/vscode-swiftformat#6]
`TypeError: Cannot read property 'uri' of undefined    at userDefinedFormatOptionsForDocument (/Users/apple/.vscode/extensions/vknabel.vscode-swiftformat-1.3.0/out/src/SwiftFormatEditProvider.js:15:36)    at format (/Users/apple/.vscode/extensions/vknabel.vscode-swiftformat-1.3.0/out/src/SwiftFormatEditProvider.js:27:33)    at SwiftFormatEditProvider.provideDocumentFormattingEdits (/Users/apple/.vscode/extensions/vknabel.vscode-swiftformat-1.3.0/out/src/SwiftFormatEditProvider.js:65:16)    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:543:107    at t.asPromise (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:50:385)    at new Promise (<anonymous>)    at Object.t.asPromise (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:50:353)    at e.provideDocumentFormattingEdits (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:543:67)    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:558:542    at e._withAdapter (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:553:292)    at e.$provideDocumentFormattingEdits (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:558:504)    at t._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:644:118)    at t._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:643:744)    at t._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:642:256)    at t._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:641:155)    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:638:960    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:38:994    at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:44:113)    at a (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:170:213)    at Socket.f._socketDataListener (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:170:434)    at Socket.emit (events.js:182:13)    at addChunk (_stream_readable.js:279:12)    at readableAddChunk (_stream_readable.js:264:11)    at Socket.Readable.push (_stream_readable.js:219:10)    at Pipe.onread (net.js:636:20)`

**Comment by joy-yu** [comment]
It happened just when I create a new swift file in VScode and try to format it.
And it work normally in other case.

**Comment by vknabel** [comment]
Thanks for your bug report!
This should be fixed in 1.3.1.
