### ISSUE TITLE
What is Package.swift

### ISSUE THREAD

**Issue by tgerk** [vknabel/vscode-swiftformat#7]
Your instructions call out a file "Package.swift"  Which app owns this file, or where are common locations to find it?

**Comment by vknabel** [comment]
@tgerk the Package.swift file is the project declaration file for Swift Package Manager projects. You can find an official introduction at [swift.org/package-manager](https://swift.org/package-manager/)

It’s mandatory for non apple platforms like Linux, and is great for building CLIs or servers.
