### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by Myk-da-Beast** [vknabel/vscode-swiftformat#8]
So does this work automatically? Does it happen when I save? If I type swiftformat . into the terminal it works but isn't that how it would behave without this extension?

**Comment by vknabel** [comment]
Hi @Myk-da-Beast!
The `swiftformat` from the terminal is the driver for this extension.

This extension adds support for the `Format document`-command for Swift files of VS Code. By default you can manually trigger it using `⇧⌥F` as in [this cheat sheet](https://code.visualstudio.com/shortcuts/keyboard-shortcuts-macos.pdf). You can also manually search for the command by opening the command palette using `⇧⌘P`. 

If you wish to automatically format documents on save add `"editor.formatOnSave": true` to your settings.
